server:
  port: 9800
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    #是否将自己注册到eureka中
    register-with-eureka: false
    #是否从eureka中获取信息
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka
